(function(root){
function demo(){return {id:'oct50',name:'Контрольный старт · Октябрь',category:'Плавание · 50 м · Кроль',closed:false,athletes:[{id:'a1',name:'Алексей Смирнов'},{id:'a2',name:'Мария Иванова'},{id:'a3',name:'Данияр Омаров'},{id:'a4',name:'Айгуль Садыкова'}],sessions:[{id:'s1',date:'2026-10-01',time:'07:00',group:'Триатлон',published:true,entries:[{athlete:'a1',attempts:['00:34.80','00:34.20']},{athlete:'a3',attempts:['00:33.50']}]},{id:'s2',date:'2026-10-01',time:'19:00',group:'Триатлон',published:false,entries:[{athlete:'a1',attempts:['00:33.10']}]},{id:'s3',date:'2026-10-02',time:'07:00',group:'Плавание',published:false,entries:[{athlete:'a2',attempts:['00:32.90']}]},{id:'s4',date:'2026-10-02',time:'19:00',group:'Плавание',published:false,entries:[{athlete:'a4',attempts:['00:33.10']}]}]};}
function parse(s){const m=/^(?:(\d{2}):)?(\d{2}):(\d{2})[.,](\d{2})$/.exec(s.trim());if(!m||+(m[1]||0)>23||+m[2]>59||+m[3]>59)return null;const t=((+(m[1]||0)*3600)+(+m[2]*60)+(+m[3]))*100+ +m[4];return t>0?t:null;}
function format(t){const h=Math.floor(t/360000);return (h?String(h).padStart(2,'0')+':':'')+String(Math.floor(t/6000)%60).padStart(2,'0')+':'+String(Math.floor(t/100)%60).padStart(2,'0')+'.'+String(t%100).padStart(2,'0');}
function leaderboard(event){const rows=new Map();for(const s of event.sessions.filter(s=>s.published)){for(const e of s.entries){for(const [i,value] of e.attempts.entries()){const t=parse(value);if(t===null)continue;let r=rows.get(e.athlete);if(!r){r={athlete:e.athlete,time:t,session:s.id,date:s.date,clock:s.time,attempt:i+1,count:0};rows.set(e.athlete,r);}r.count++;if(t<r.time)Object.assign(r,{time:t,session:s.id,date:s.date,clock:s.time,attempt:i+1});}}}const sorted=[...rows.values()].sort((a,b)=>a.time-b.time||a.athlete.localeCompare(b.athlete));return sorted.map(r=>({...r,rank:sorted.findIndex(a=>a.time===r.time)+1}));}
function publish(event,id){if(event.closed)throw Error('Старт закрыт');const s=event.sessions.find(s=>s.id===id);if(!s)throw Error('Сессия не найдена');if(s.published)return;if(!s.entries.length)throw Error('Добавьте участников');if(new Set(s.entries.map(e=>e.athlete)).size!==s.entries.length)throw Error('Участник повторяется в сессии');if(s.entries.some(e=>!event.athletes.some(a=>a.id===e.athlete)||!e.attempts.length||e.attempts.some(v=>parse(v)===null)))throw Error('Заполните все попытки: мм:сс.сс или чч:мм:сс.сс; минуты и секунды 00–59, часы 00–23, время больше нуля');s.published=true;}
function close(event){if(event.closed)return;if(!event.sessions.length||event.sessions.some(s=>!s.published))throw Error('Сначала опубликуйте все сессии. Это ограничение прототипа.');event.closed=true;}
const api={demo,parse,format,leaderboard,publish,close};if(typeof module!=='undefined')module.exports=api;else root.Sessions=api;
})(typeof window==='undefined'?globalThis:window);
