(function(root){
function demo(){return {id:'oct50',name:'Контрольный старт · Октябрь',category:'Плавание · 50 м · Кроль',closed:false,athletes:[{id:'a1',name:'Алексей Смирнов'},{id:'a2',name:'Мария Иванова'},{id:'a3',name:'Данияр Омаров'},{id:'a4',name:'Айгуль Садыкова'}],sessions:[{id:'s1',date:'2026-10-01',time:'07:00',group:'Триатлон',published:true,entries:[{athlete:'a1',attempts:['00:34.80','00:34.20']},{athlete:'a3',attempts:['00:33.50']}]},{id:'s2',date:'2026-10-01',time:'19:00',group:'Триатлон',published:false,entries:[{athlete:'a1',attempts:['00:33.10']}]},{id:'s3',date:'2026-10-02',time:'07:00',group:'Плавание',published:false,entries:[{athlete:'a2',attempts:['00:32.90']}]},{id:'s4',date:'2026-10-02',time:'19:00',group:'Плавание',published:false,entries:[{athlete:'a4',attempts:['00:33.10']}]}]};}
function parse(s){const m=/^(?:(\d{2}):)?(\d{2}):(\d{2})[.,](\d{2})$/.exec(s.trim());if(!m||+(m[1]||0)>23||+m[2]>59||+m[3]>59)return null;const t=((+(m[1]||0)*3600)+(+m[2]*60)+(+m[3]))*100+ +m[4];return t>0?t:null;}
function format(t){const h=Math.floor(t/360000);return (h?String(h).padStart(2,'0')+':':'')+String(Math.floor(t/6000)%60).padStart(2,'0')+':'+String(Math.floor(t/100)%60).padStart(2,'0')+'.'+String(t%100).padStart(2,'0');}
function leaderboard(event){const rows=new Map();for(const s of event.sessions.filter(s=>s.published)){for(const e of s.entries){for(const [i,value] of e.attempts.entries()){const t=parse(value);if(t===null)continue;let r=rows.get(e.athlete);if(!r){r={athlete:e.athlete,time:t,session:s.id,date:s.date,clock:s.time,attempt:i+1,count:0};rows.set(e.athlete,r);}r.count++;if(t<r.time)Object.assign(r,{time:t,session:s.id,date:s.date,clock:s.time,attempt:i+1});}}}const sorted=[...rows.values()].sort((a,b)=>a.time-b.time||a.athlete.localeCompare(b.athlete));return sorted.map(r=>({...r,rank:[...new Set(sorted.map(a=>a.time))].indexOf(r.time)+1}));}
function publish(event,id){if(event.closed)throw Error('Старт закрыт');const s=event.sessions.find(s=>s.id===id);if(!s)throw Error('Сессия не найдена');if(s.published)return;if(!s.entries.length)throw Error('Добавьте участников');if(new Set(s.entries.map(e=>e.athlete)).size!==s.entries.length)throw Error('Участник повторяется в сессии');if(s.entries.some(e=>!event.athletes.some(a=>a.id===e.athlete)||!e.attempts.length||e.attempts.some(v=>parse(v)===null)))throw Error('Заполните все попытки: мм:сс.сс или чч:мм:сс.сс; минуты и секунды 00–59, часы 00–23, время больше нуля');s.published=true;}
function close(event){if(event.closed)return;if(!event.sessions.length||event.sessions.some(s=>!s.published))throw Error('Сначала опубликуйте все сессии. Это ограничение прототипа.');event.closed=true;}
function addSession(event,values){if(event.closed)throw Error('Старт закрыт');const group=String(values.group||'').trim();if(!group)throw Error('Укажите группу или название сессии');if(group.length>80)throw Error('Название — не более 80 символов');const date=String(values.date||''),time=String(values.time||'');if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date+'T12:00:00Z'))||new Date(date+'T12:00:00Z').toISOString().slice(0,10)!==date)throw Error('Укажите корректную дату');if(!/^([01]\d|2[0-3]):[0-5]\d$/.test(time))throw Error('Укажите время начала от 00:00 до 23:59');let n=event.sessions.length+1;while(event.sessions.some(s=>s.id==='s'+n))n++;const session={id:'s'+n,date,time,group,published:false,entries:[]};event.sessions.push(session);return session;}
function mask(value,hours=false){const d=String(value).replace(/\D/g,'').slice(0,hours?8:6);const cuts=hours?[2,4,6]:[2,4];let out='';for(let i=0;i<d.length;i++){if(cuts.includes(i))out+=i===(hours?6:4)?'.':':';out+=d[i]}return out;}
function attemptsLabel(n){const a=n%100,b=n%10;return n+' '+(a>=11&&a<=14?'попыток':b===1?'попытка':b>=2&&b<=4?'попытки':'попыток');}
function deleteDraft(event,id){if(event.closed)throw Error('Старт закрыт');const index=event.sessions.findIndex(s=>s.id===id);if(index<0)throw Error('Сессия не найдена');if(event.sessions[index].published)throw Error('Опубликованную сессию удалить нельзя');event.sessions.splice(index,1);}
const api={demo,parse,format,leaderboard,publish,close,addSession,mask,attemptsLabel,deleteDraft};if(typeof module!=='undefined')module.exports=api;else root.Sessions=api;
})(typeof window==='undefined'?globalThis:window);
